Umbra_Database = {
    ["Elonmunk-TarrenMill"] = {
        role = "tank",
        spec = "Brewmaster",
        grade = "A-",
        dps_perf = 59,
        dps_ilvl = 72,
        utility = 40,
        survivability = 65,
        cd_usage = 100,
        cpm = 97,
        timed_pct = 67,
        runs = 22,
    },
    ["Dobbermon-TarrenMill"] = {
        role = "healer",
        spec = "Restoration",
        grade = "B+",
        throughput = 38,
        dps_perf = 57,
        dps_ilvl = 60,
        utility = 86,
        survivability = 41,
        cd_usage = 100,
        cpm = 100,
        timed_pct = 67,
        runs = 16,
    },
}
